title: Site
unlisted: true
options: 
  url: false
  status: true
  delete: true
pages:
  template:
    - section
columns:
  - width: 1/1
    sections:
      drafts:
        headline: Drafts
        layout: list
        status: drafts
        type: pages
      unlisted: 
        headline: Unpublished Pages
        layout: list
        status: unlisted
        type: pages
      listed: 
        headline: Published Pages
        layout: list
        status: listed
        max: 14
        type: pages
  - width: 1/1
    sections:
      gallery:
        headline: Site-wide Files
        type: files
        template: gallery

  - width: 1/2
    sections:
      sitefooter:
        type: fields
        fields:
          contactsection:
            label: Contact Section
            type: headline          
          contacttitle:
            label: Contact Section Title
            type: text
            default: Contact
            required: true
            width: 2/3
          contactvisibility:
            label: Show Section
            type: toggle
            default: true
            text:
              - Hiding
              - Showing
            width: 1/3
          contactcontent:
            label: Contact Tab Content
            type: textarea
            size: large

          trailersection:
            label: Trailer Section
            type: headline          
          trailertitle:
            label: Trailer Section Title
            type: text
            default: Trailer
            required: true
            width: 2/3
          trailervisibility:
            label: Show Section
            type: toggle
            default: true
            text:
              - Hiding
              - Showing
            width: 1/3
          trailerpopup:
            label: Pop up
            type: toggle
            default: true
            text:
              - Pop-up on click
              - Load Pop-up
            width: 1/2
          trailerlink:
            label: Vimeo ID
            type: text
            help: (found in the url)
            width: 1/2
            
  - width: 1/2
    sections:
      siteinfo:
        type: fields
        fields:
          brochuresection:
            label: Brochure Section
            type: headline
          brochuretitle:
            label: Brochure Section Title
            type: text
            default: Brochure
            required: true
            width: 2/3
          brochurevisibility:
            label: Show Section
            type: toggle
            default: true
            text:
              - Hiding
              - Showing
            width: 1/3
          brochurefile:
            label: File for Displaying
            type: files
            multiple: false
            query: site.files

          seosection:
            label: SEO Section
            type: headline
          seodescription:
            label: SEO Description
            type: textarea
            size: small
          seotags:
            label: SEO Tags
            type: tags
            size: small
          seoimage:
            label: SEO Image
            type: files
            query: site.images
          favicon:
            label: Favicon
            type: files
            query: site.images